Repository ProctorU/guides, pull requests merged in 2018-06, with the labels that each got.

#45 Improve rubocop configuration file
  style/ruby/.rubocop.yml
Labels: Status: Review Complete, Type: Feature

#44 Add Code Review checklist
  code-review/README.md
Labels: Status: Review Complete, Status: Revised, Type: Feature

#46 Add guide for better assertions
  style/ruby/README.md
Labels: Status: Ready To Ship, Type: Feature

#48 Update rails tips with collection rendering via partials
  rails-tips/README.md
Labels: Type: Feature
